import pandas as pd
df=pd.read_csv(r"Data\Raw\restaurant_sales_data.csv")
print("The dimensions of the dataframe are:\n",df.shape)
print("\nThe column names are:\n",df.columns.tolist())
print("\nThe first 5 rows of the dataframe are:\n",df.head())
print("\nThe last 5 rows of the dataframe are:\n",df.tail())
print("\nDataframe information:\n",df.info())
print("\nThe data types are:\n",df.dtypes)
print("\nNumber of duplicated rows:\n",df.duplicated().sum())
print("\nStatistical summary:\n",df.describe())
print("\nNumber of unique values in each column:\n",df.nunique())
print("\nNumber of missing values in each column:\n",df.isnull().sum())
